version: '3.8'
services:
  app:
    build: .
    container_name: digimon-api
    ports:
      - "5431:5431"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/digimondb
      SPRING_JPA_HIBERNATE_DDL_AUTO: none
    depends_on:
      - db
    networks:
      - digimon-network

  db:
    image: postgres:14
    container_name: digimon-postgres
    environment:
      POSTGRES_DB: digimondb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - digimon-network

volumes:
  postgres_data:

networks:
  digimon-network:
