version: '3.8'
services:
  postgres:
    image: postgres:15
    container_name: digimon-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: digimonapi
    ports:
      - "5432:5432"  # Expose PostgreSQL on port 5432
    volumes:
      - postgres_data:/var/lib/postgresql/data  # Persist database data
    networks:
      - digimon-network

  springboot-app:
    build: .
    container_name: digimon-api
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/digimonapi
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
    ports:
      - "5431:5431"  # Expose Spring Boot application on port 5431
    depends_on:
      - postgres
    networks:
      - digimon-network

networks:
  digimon-network:
    driver: bridge

volumes:
  postgres_data:
